# Generated by Django 3.2.6 on 2022-07-26 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default='getting-started'),
            preserve_default=False,
        ),
    ]
